"""Comment and Post Like Models

Revision ID: 037fd18673c3
Revises: e2a1e2bef934
Create Date: 2023-06-18 00:58:08.148477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037fd18673c3'
down_revision = 'e2a1e2bef934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PostLikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PostLikes_timestamp'), 'PostLikes', ['timestamp'], unique=False)
    op.create_table('CommentLikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CommentLikes_timestamp'), 'CommentLikes', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vending_coin', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_CommentLikes_timestamp'), table_name='CommentLikes')
    op.drop_table('CommentLikes')
    op.drop_index(op.f('ix_PostLikes_timestamp'), table_name='PostLikes')
    op.drop_table('PostLikes')
    # ### end Alembic commands ###
