"""Comment DisLike Models

Revision ID: 03de503a00f1
Revises: 96798d565cc3
Create Date: 2023-06-18 12:38:27.532687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03de503a00f1'
down_revision = '96798d565cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CommentDislikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CommentDislikes_timestamp'), 'CommentDislikes', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vending_coin', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_CommentDislikes_timestamp'), table_name='CommentDislikes')
    op.drop_table('CommentDislikes')
    # ### end Alembic commands ###
