"""coin recharge

Revision ID: 0cdc733c11ee
Revises: e5d7aac92ed1
Create Date: 2021-05-17 17:34:23.386724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdc733c11ee'
down_revision = 'e5d7aac92ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CoinRechargeCodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('moderator_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_CoinRechargeCodes_timestamp'), 'CoinRechargeCodes', ['timestamp'], unique=False)
    op.add_column('CoinTransactions', sa.Column('body', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CoinTransactions', 'body')
    op.drop_index(op.f('ix_CoinRechargeCodes_timestamp'), table_name='CoinRechargeCodes')
    op.drop_table('CoinRechargeCodes')
    # ### end Alembic commands ###
