"""recharge with budget CoinPackage

Revision ID: 2a94604981e7
Revises: c3cb949649cf
Create Date: 2025-01-14 19:51:54.839113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a94604981e7'
down_revision = 'c3cb949649cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin_packages', sa.Column('limited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vending_coin', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'trackings', type_='foreignkey')
    op.drop_column('coin_packages', 'limited')
    op.drop_constraint(None, 'CommentDislikes', type_='foreignkey')
    op.create_foreign_key(None, 'CommentDislikes', 'posts', ['comment_id'], ['id'])
    # ### end Alembic commands ###
