"""Hooking Connection Model

Revision ID: 37371a749b8b
Revises: 989e85ee0443
Create Date: 2023-08-26 03:10:56.122907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37371a749b8b'
down_revision = '989e85ee0443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ConnectHooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'sender_id', 'receiver_id')
    )
    op.add_column('web_datas', sa.Column('connection_fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_datas', 'connection_fee')
    op.drop_table('ConnectHooks')
    # ### end Alembic commands ###
