"""winning logic added

Revision ID: 3793ebc4b574
Revises: 9b9d647f528c
Create Date: 2024-11-10 04:51:35.670846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3793ebc4b574'
down_revision = '9b9d647f528c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('winnings', sa.Column('celebrity_id', sa.Integer(), nullable=True))
    op.add_column('winnings', sa.Column('days_b4_expiration', sa.Integer(), nullable=True))
    op.add_column('winnings', sa.Column('referral_id', sa.String(length=32), nullable=True))
    op.add_column('winnings', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('winnings', 'timestamp')
    op.drop_column('winnings', 'referral_id')
    op.drop_column('winnings', 'days_b4_expiration')
    op.drop_column('winnings', 'celebrity_id')
    op.add_column('users', sa.Column('vending_coin', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'CommentDislikes', type_='foreignkey')
    op.create_foreign_key(None, 'CommentDislikes', 'posts', ['comment_id'], ['id'])
    # ### end Alembic commands ###
