"""message recipe is deletable added

Revision ID: 3ca898bab9f7
Revises: 9d6c1f7c7f7e
Create Date: 2024-09-25 14:25:36.564123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ca898bab9f7'
down_revision = '9d6c1f7c7f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MessageRecipes', sa.Column('is_deletable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MessageRecipes', 'is_deletable')
    # ### end Alembic commands ###
