"""vending coin in user

Revision ID: 3f21c89dc522
Revises: 0cdc733c11ee
Create Date: 2021-05-22 03:34:18.126763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f21c89dc522'
down_revision = '0cdc733c11ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vending_coin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vending_coin')
    # ### end Alembic commands ###
