"""tracking_history_image_url and winning model

Revision ID: 4af41717d97a
Revises: 0a407895d296
Create Date: 2024-10-06 01:59:25.162690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af41717d97a'
down_revision = '0a407895d296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_winnings_name'), 'winnings', ['name'], unique=False)
    op.add_column('tracking_histories', sa.Column('image_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vending_coin', sa.INTEGER(), nullable=True))
    op.drop_column('tracking_histories', 'image_url')
    op.drop_constraint(None, 'CommentDislikes', type_='foreignkey')
    op.create_foreign_key(None, 'CommentDislikes', 'posts', ['comment_id'], ['id'])
    op.drop_index(op.f('ix_winnings_name'), table_name='winnings')
    op.drop_table('winnings')
    # ### end Alembic commands ###
