"""user validated for work

Revision ID: 53154e1d0082
Revises: 4699e3366b6d
Create Date: 2023-07-10 06:39:09.590524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53154e1d0082'
down_revision = '4699e3366b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('validated_for_work', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'validated_for_work')
    # ### end Alembic commands ###
