"""e

Revision ID: 6118bfba3e03
Revises: 44e33c7b14cc
Create Date: 2023-06-27 23:02:50.480601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6118bfba3e03'
down_revision = '44e33c7b14cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_datas', sa.Column('exchange_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_datas', 'exchange_rate')
    # ### end Alembic commands ###
