"""WebData usps and page charges added

Revision ID: 701505519e9e
Revises: 4af41717d97a
Create Date: 2024-10-17 00:44:24.290544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701505519e9e'
down_revision = '4af41717d97a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_datas', sa.Column('page_fee', sa.Integer(), nullable=True))
    op.add_column('web_datas', sa.Column('usps_track_fee', sa.Integer(), nullable=True))
    op.add_column('web_datas', sa.Column('usps_track_history_fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_datas', 'usps_track_history_fee')
    op.drop_column('web_datas', 'usps_track_fee')
    op.drop_column('web_datas', 'page_fee')
    op.add_column('users', sa.Column('vending_coin', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'CommentDislikes', type_='foreignkey')
    op.create_foreign_key(None, 'CommentDislikes', 'posts', ['comment_id'], ['id'])
    # ### end Alembic commands ###
