"""celebrity models

Revision ID: 74b165f4ad51
Revises: f7d87efd5d11
Create Date: 2024-08-13 17:10:47.457259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b165f4ad51'
down_revision = 'f7d87efd5d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celebrities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_celebrities_name'), 'celebrities', ['name'], unique=False)
    op.create_index(op.f('ix_celebrities_username'), 'celebrities', ['username'], unique=True)
    op.create_table('CelebrityLogos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('celebrity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['celebrity_id'], ['celebrities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CelebrityPictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('celebrity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['celebrity_id'], ['celebrities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vending_coin', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'CommentDislikes', type_='foreignkey')
    op.create_foreign_key(None, 'CommentDislikes', 'posts', ['comment_id'], ['id'])
    op.drop_table('CelebrityPictures')
    op.drop_table('CelebrityLogos')
    op.drop_index(op.f('ix_celebrities_username'), table_name='celebrities')
    op.drop_index(op.f('ix_celebrities_name'), table_name='celebrities')
    op.drop_table('celebrities')
    # ### end Alembic commands ###
