"""checkings

Revision ID: 93f20096a413
Revises: a4cf6f088385
Create Date: 2023-10-17 03:02:34.223278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f20096a413'
down_revision = 'a4cf6f088385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vending_coin', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'CommentDislikes', type_='foreignkey')
    op.create_foreign_key(None, 'CommentDislikes', 'posts', ['comment_id'], ['id'])
    # ### end Alembic commands ###
