"""Post DisLike Models

Revision ID: 96798d565cc3
Revises: 15bf4f74a77e
Create Date: 2023-06-18 12:32:19.422196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96798d565cc3'
down_revision = '15bf4f74a77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vending_coin', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
