"""post is_news

Revision ID: 989e85ee0443
Revises: 53154e1d0082
Create Date: 2023-07-14 00:32:32.822967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989e85ee0443'
down_revision = '53154e1d0082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_news', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_news')
    # ### end Alembic commands ###
