"""transaction point

Revision ID: 9a005c43fe96
Revises: 6118bfba3e03
Create Date: 2023-07-09 23:38:38.957336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a005c43fe96'
down_revision = '6118bfba3e03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('point', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'point')
    # ### end Alembic commands ###
