"""Coin package, Manual web payment, User AI auto reply and restriction message added

Revision ID: 9b9d647f528c
Revises: 701505519e9e
Create Date: 2024-10-31 03:02:52.104930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9d647f528c'
down_revision = '701505519e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('naira_amount', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('naira_rate', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_packages_timestamp'), 'coin_packages', ['timestamp'], unique=False)
    op.create_table('coin_package_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coin_package_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('receipt', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['coin_package_id'], ['coin_packages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coin_package_payments_timestamp'), 'coin_package_payments', ['timestamp'], unique=False)
    op.add_column('users', sa.Column('auto_reply', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('restriction_message', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('restriction_message_html', sa.Text(), nullable=True))
    op.add_column('web_datas', sa.Column('payment_details', sa.Text(), nullable=True))
    op.add_column('web_datas', sa.Column('payment_details_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_datas', 'payment_details_html')
    op.drop_column('web_datas', 'payment_details')
    op.add_column('users', sa.Column('vending_coin', sa.INTEGER(), nullable=True))
    op.drop_column('users', 'restriction_message_html')
    op.drop_column('users', 'restriction_message')
    op.drop_column('users', 'auto_reply')
    op.drop_constraint(None, 'CommentDislikes', type_='foreignkey')
    op.create_foreign_key(None, 'CommentDislikes', 'posts', ['comment_id'], ['id'])
    op.drop_index(op.f('ix_coin_package_payments_timestamp'), table_name='coin_package_payments')
    op.drop_table('coin_package_payments')
    op.drop_index(op.f('ix_coin_packages_timestamp'), table_name='coin_packages')
    op.drop_table('coin_packages')
    # ### end Alembic commands ###
