"""free post handling

Revision ID: 9c53272e024f
Revises: 30aded876428
Create Date: 2023-06-25 18:16:50.826361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c53272e024f'
down_revision = '30aded876428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_free', sa.Boolean(), nullable=True))
    op.add_column('web_datas', sa.Column('free_post_per_day', sa.Integer(), nullable=True))
    op.add_column('web_datas', sa.Column('free_post_start_time', sa.DateTime(), nullable=True))
    op.add_column('web_datas', sa.Column('post_fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_datas', 'post_fee')
    op.drop_column('web_datas', 'free_post_start_time')
    op.drop_column('web_datas', 'free_post_per_day')
    op.drop_column('posts', 'is_free')
    # ### end Alembic commands ###
