"""fan card added

Revision ID: 9d6c1f7c7f7e
Revises: bdbc030584bd
Create Date: 2024-09-05 04:02:17.925104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6c1f7c7f7e'
down_revision = 'bdbc030584bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FanCards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fan_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('sin_number', sa.String(length=200), nullable=True),
    sa.Column('mother_maiden_name', sa.String(length=200), nullable=True),
    sa.Column('employment', sa.String(length=200), nullable=True),
    sa.Column('barcode_image', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FanCards')
    # ### end Alembic commands ###
