"""Post reward point

Revision ID: b1419510dbdf
Revises: 03de503a00f1
Create Date: 2023-06-19 22:19:39.114957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1419510dbdf'
down_revision = '03de503a00f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('reward_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'reward_points')
    # ### end Alembic commands ###
