"""User as fan and celebrity connect

Revision ID: bdbc030584bd
Revises: 74b165f4ad51
Create Date: 2024-08-13 14:28:57.709885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbc030584bd'
down_revision = '74b165f4ad51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Altering the 'celebrities' table to add the 'verified' column
    with op.batch_alter_table('celebrities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
    
    # Altering the 'users' table to add the 'celebrity_id' column and foreign key
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celebrity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            constraint_name='fk_users_celebrity_id',  # Provide a name for the foreign key constraint
            referent_table='celebrities',
            local_cols=['celebrity_id'],
            remote_cols=['id']
        )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Reverting the foreign key and column changes in 'users' table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_celebrity_id', type_='foreignkey')
        batch_op.drop_column('celebrity_id')
    
    # Reverting the column change in 'celebrities' table
    with op.batch_alter_table('celebrities', schema=None) as batch_op:
        batch_op.drop_column('verified')
    
    # ### end Alembic commands ###
