"""fake_coin

Revision ID: d315a5767a37
Revises: 93f20096a413
Create Date: 2023-10-19 02:34:25.804713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd315a5767a37'
down_revision = '93f20096a413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fake_coin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fake_coin')
    # ### end Alembic commands ###
