"""Add referral id

Revision ID: e2a1e2bef934
Revises: 4959cf1cffeb
Create Date: 2023-06-17 11:19:39.923597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a1e2bef934'
down_revision = '4959cf1cffeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vending_coin', sa.INTEGER(), nullable=True))
    op.drop_column('users', 'referral_id')
    # ### end Alembic commands ###
